apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize
  prune: true
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: podinfo
  ingress:
    enabled: true
    className: ""
    hosts:
      - host: podinfo.tasenko.ru
        paths:
          - path: /
            pathType: ImplementationSpecific
