apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus
  namespace: monitoring
spec:
  interval: 10m
  targetNamespace: monitoring
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
  path: "manifests/setup"
  prune: true
  timeout: 1m
