apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: monitoring
spec:
  releaseName: kube-prometheus
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus
      sourceRef:
        kind: OCIRepository
        name: kube-prometheus
        namespace: monitoring
