---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    apiToken: AgDkUTa7xPNy+7F/enfKLSuzSC+Cp6wutPiVwuYcjXyUKdtF4LnlBFTg8MibLtxIcnhLVB3D5UFLBhJCGPHDsXf6Kh/aAA8fa5mPv1Wpx4ELakQN1KEOndo8eDcbbWAIXTNRSeOk59TSINRdQkRnHVL4FGScAcxQ6dEGBgLydRAbGTGU4fIItJRT+8Qk7XPAqLyyy266vb5p5XjjbUSaucn584PZ8pb7qIvMd8abNiUe9vJ242jA5y6+vn5BqlYvpYxXpGShE0Y6LH/8+vsgVpPXTjaKmDcXEOzX2MVgmgJSKWSZVr1GzB9lG/8JchdqNJhUzb2XEkhfXB11QQVN4PHJToQ3Pz9MyAh/naLS0ngrG2MumCeETqW81cSGGH8UoR5siY+BNCgfD/qQcbX4AGqO8p35H9wmTnlITgNSt8fYkjdgC5N1eNp0cAhiDkbQga+2dt5AVYyYnOrgBI6Y+9NTl2lI6f+BRO3NAyQXibGWNJhROU+bskE8ZGzSni5kesl7pcjLjYtuTS4Sxd4bfrQlhPLmC0AkM1+8QHMvxoU29tiKjW3ZzjY6z3xvoyvTTh+nDLz6vjtUqfM+la2uFzUhsfsWhvcaHoI5VZVgsdjFbG71S+pvhnVQq8iGGyl6H8k8ZVYB8KDr//D1gxKA9wkZVJkfdoubMl+QpLYyzvVN9cQMARXfDQREPBnAMSqXPOUpcBQhv3h5qAAn3WErkRvwmxwpiwjoLY5+3eyk3JDViwy/WqBBx+tL
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
