apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: a@tasenko.ru
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
          - "tasenko.ru"
      dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: apiToken
