apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: a@tasenko.ru
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
          - "tasenko.ru"
          - "nginx.tasenko.ru"
      dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: apiToken
