apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      chart: podinfo
      version: 6.x
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: podinfo
  interval: 15m
  timeout: 5m
  releaseName: podinfo
  values:
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
        cert-manager.io/cluster-issuer: letsencrypt-staging
      hosts:
        - host: "podinfo.tasenko.ru"
          paths:
            path: /
  #  tls:
  #  - secretName: letsencrypt-staging
  #    hosts:
  #      - podinfo.tasenko.ru
